취향 조회, 수정, 삭제 기능 구현
Dongguk-Hackaton/omo-spring-boot-app pull request #24
Opened 2024-07-13 05:01 UTC by daegyu-song

취향 조회, 수정, 삭제 기능 구현했습니다.

2024-07-13 07:50 UTC, minnnisu requested changes
각 코드 마다 수정해야할 부분에 대해 코멘트를 작성해두었습니다.
내용을 정리하면 다음과 같습니다.
- ResponseDto 수정
- findById에서 findByEntity로 수정 - [참고자료](https://bcp0109.tistory.com/305)
- 테이블 수정 시 삭제 및 추가에 대한 저의 견해

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        TasteProfile tasteProfile = tasteProfileRepository.findByUserId(user.getId());
63번째줄부터 67번줄까지 다음과 같이 축약해서 나타낼 수 있을 거 같아요.
제가 쓴 코드의 문법이 맞는지 다시 한번 체크해주세요.

 ```
TasteProfile tasteProfile = tasteProfileRepository.findByUser(user).orElseThrow(() -> new CustomErrorException(ErrorCode.TasteProfileNotFoundError));
```

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/dto/taste/TasteDeleteResponseDto.java
> +public class TasteDeleteResponseDto {
삭제된 정보를 클라이언트가 볼 수 있도록 추가해주세요
- 취향 프로필 아이디
- 삭제일자

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/dto/taste/TastePatchResponseDto.java
> +public class TastePatchResponseDto {
업데이트된 정보를 클라이언트가 볼 수 있도록 추가해주세요
- 취향 프로필 아이디
- 업데이트일자 -> LocalDateTime.now() 사용

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        List<DislikedFood> dislikedFoodList = dislikedFoodRepository.findByTasteProfileId(tasteProfileId);
`dislikedFoodRepository.findByTasteProfile(tasteProfile)`를 사용해주세요

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        List<FavoriteFood> favoriteFoodList = favoriteFoodRepository.findByTasteProfileId(tasteProfileId);
`findByTasteProfile(tasteProfile)`로 바꿔서 해주세요

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        TasteProfile tasteProfile = tasteProfileRepository.findByUserId(user.getId());
`tasteProfileRepository.findByUser(user)`를 사용해주세요

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        dislikedFoodRepository.deleteByTasteProfileId(tasteProfileId);
`dislikedFoodRepository.deleteByTasteProfile(tasteProfile)`를 사용해주세요

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        favoriteFoodRepository.deleteByTasteProfileId(tasteProfileId);
`favoriteFoodRepository.deleteByTasteProfile(tasteProfile)`를 사용해주세요

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        TasteProfile tasteProfile = tasteProfileRepository.findByUserId(user.getId());
TasteProfile tasteProfile = tasteProfileRepository.findByUser(user);

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +        favoriteFoodRepository.deleteByTasteProfileId(tasteProfileId);
dislikedFoodRepository.deleteByTasteProfile(tasteProfile);
favoriteFoodRepository.deleteByTasteProfile(tasteProfile);

2024-07-13 07:50 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +
patch를 할때 기존에 저장된 favorite 및 dislikedFood들을 삭제하고 다시 생성하던데 이유가 있을까요?
저 개인적인 생각으로는 굳이 삭제를 하지 않고 이미 저장된 값들을 찾고 수정하는 방향으로 가도 괜찮다고 생각하거든요

2024-07-13 07:57 UTC, daegyu-song commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +
patch 동작 원리에 대한 이해가 부족했습니다. 수정하겠습니다

2024-07-13 07:58 UTC, daegyu-song commented
감사합니다

2024-07-15 04:05 UTC, minnnisu approved these changes
코멘트에 대한 수정사항을 확인했습니다.
잘 된 것 같네요!

2024-07-15 04:05 UTC, minnnisu commented on src/main/java/org/omo/omospringboot/service/taste/TasteService.java
> +
아 수정말고 제거 후 추가가 맞군요.
제가 착각했네요😅

2024-07-15 04:23 UTC, minnnisu approved these changes

2024-07-15 04:23 UTC, merged